sonata_admin:
  title: 'Sonata Admin'
  dashboard:
    groups:
      api:
        label: АПИ
      user:
        label: Пользователи
    blocks:
      - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
  blocks:
    sonata.admin.block.admin_list:
      contexts: [ admin ]
