version: '3.6'

networks:
  backend: ~
  traefik:
    name: ${TRAEFIK_NETWORK_NAME}
    external: true

services:
  http:
    image: nginx
    hostname: swagger.docker
    depends_on:
      - php-fpm
    labels:
      - traefik.enable=true
      - traefik.docker.network=${TRAEFIK_NETWORK_NAME}
      - "traefik.http.routers.swagger.rule=Host(`swagger.docker`)"
    environment:
      - NGINX_HOST=swagger.docker
      - NGINX_PORT=80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
    networks:
      - backend
      - traefik

  php-fpm:
    build:
      context: docker/php
      args:
        USER_ID: ${DOCKER_USER_UID}
        USER_NAME: ${DOCKER_USER_NAME}
        GROUP_ID: ${DOCKER_GROUP_ID}
    depends_on:
      - database
    networks:
      - backend
    volumes:
      - .:/var/www
      - ${PRIVATE_SSH_KEY}:/home/${DOCKER_USER_NAME}/.ssh/id_rsa

  node:
    image: node
    user: 1000:1000
    working_dir: /var/www
    volumes:
      - .:/var/www

  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    networks:
      - backend
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw

